insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Betty', 'Fisher', 'password', 'bfisher0@salon.com', 'Denver', '2016-04-01 10:56:53', 59, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Julia', 'Dixon', 'password', 'jdixon1@cpanel.net', 'Qiucun', '2016-02-26 05:05:58', 20, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Dorothy', 'Frazier', 'password', 'dfrazier2@google.com.br', 'Vista Hermosa', '2016-07-02 19:16:29', 67, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Timothy', 'Wheeler', 'password', 'twheeler3@goo.ne.jp', 'Yanjiang', '2016-03-13 07:06:18', 56, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Amy', 'Fields', 'password', 'afields4@photobucket.com', 'Västerås', '2016-03-22 09:23:43', 43, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Marilyn', 'Powell', 'password', 'mpowell5@sina.com.cn', 'Vidago', '2016-10-20 15:07:45', 21, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Todd', 'Taylor', 'password', 'ttaylor6@issuu.com', 'Krapyak Kidul', '2016-05-24 01:01:53', 100, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Katherine', 'Lane', 'password', 'klane7@columbia.edu', 'Yamazakichō-nakabirose', '2016-01-22 04:12:05', 18, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Earl', 'Rogers', 'password', 'erogers8@dot.gov', 'Opatov', '2016-06-27 16:26:04', 69, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Carlos', 'Fox', 'password', 'cfox9@friendfeed.com', 'Tsetsegnuur', '2016-09-14 05:31:28', 62, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Barbara', 'Watkins', 'password', 'bwatkinsa@tamu.edu', 'Kveda Chkhorots’q’u', '2016-02-24 07:48:26', 33, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Amanda', 'Green', 'password', 'agreenb@nps.gov', 'Passos', '2016-03-04 05:59:49', 38, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Johnny', 'Tucker', 'password', 'jtuckerc@nifty.com', 'Port Harcourt', '2016-01-09 09:51:41', 22, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Ann', 'Watkins', 'password', 'awatkinsd@yandex.ru', 'Banjarmasin', '2016-03-13 03:39:48', 42, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Kathleen', 'Flores', 'password', 'kflorese@google.it', 'Sumurgung', '2016-10-13 09:45:53', 33, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Richard', 'Daniels', 'password', 'rdanielsf@goo.gl', 'Sidokumpul', '2016-06-09 03:36:29', 68, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jerry', 'Lynch', 'password', 'jlynchg@nature.com', 'Telheira', '2016-03-13 14:12:48', 51, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Teresa', 'Ramirez', 'password', 'tramirezh@hostgator.com', 'Piracicaba', '2016-09-09 21:36:09', 30, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Beverly', 'Garza', 'password', 'bgarzai@friendfeed.com', 'Pueblo Nuevo', '2016-09-21 03:52:44', 17, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Philip', 'Crawford', 'password', 'pcrawfordj@seattletimes.com', 'Sabana Grande de Boyá', '2016-10-20 11:05:03', 90, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Martin', 'Webb', 'password', 'mwebbk@google.fr', 'Jaguaribe', '2016-01-30 08:37:41', 97, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Philip', 'Bailey', 'password', 'pbaileyl@cafepress.com', 'Kangmei', '2016-01-02 05:20:48', 98, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Lillian', 'Ward', 'password', 'lwardm@qq.com', 'Mỹ Thọ', '2016-09-09 12:02:54', 71, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('William', 'Parker', 'password', 'wparkern@tmall.com', 'Bertoua', '2016-04-29 22:27:58', 94, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Nicholas', 'Carter', 'password', 'ncartero@amazon.com', 'Bugko', '2016-10-10 22:02:29', 27, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jesse', 'Henry', 'password', 'jhenryp@seattletimes.com', 'Przemyśl', '2016-01-07 01:38:56', 48, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Rebecca', 'Evans', 'password', 'revansq@php.net', 'Templeogue', '2016-04-08 01:16:04', 63, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Dorothy', 'Hayes', 'password', 'dhayesr@photobucket.com', 'Nagareyama', '2016-07-31 03:48:01', 97, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Steven', 'Harris', 'password', 'sharriss@usnews.com', 'Dukuhmencek Lor', '2016-02-23 03:30:06', 16, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Thomas', 'Martinez', 'password', 'tmartinezt@samsung.com', 'Genengan Kulon', '2016-02-24 16:58:32', 49, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jack', 'Stephens', 'password', 'jstephensu@wix.com', 'Camias', '2016-06-11 08:43:20', 13, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Aaron', 'Hicks', 'password', 'ahicksv@berkeley.edu', 'Yanggan', '2016-06-21 14:41:15', 71, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Laura', 'Lawrence', 'password', 'llawrencew@plala.or.jp', 'Laranganglintong', '2016-02-02 22:27:11', 74, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Judy', 'Mccoy', 'password', 'jmccoyx@live.com', 'Nggalak', '2016-03-31 09:40:34', 14, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Maria', 'Carr', 'password', 'mcarry@newsvine.com', 'Masaran', '2016-06-21 03:11:30', 72, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Philip', 'Payne', 'password', 'ppaynez@pen.io', 'Bambakashat', '2016-10-15 02:37:15', 8, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Kathryn', 'Berry', 'password', 'kberry10@miibeian.gov.cn', 'Mardakyany', '2016-09-06 01:50:18', 51, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Doris', 'Sanchez', 'password', 'dsanchez11@seattletimes.com', 'Xianqiao', '2016-05-31 01:41:42', 2, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Roy', 'Ramos', 'password', 'rramos12@hc360.com', 'Pilar', '2016-05-04 12:47:50', 84, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jane', 'Hayes', 'password', 'jhayes13@auda.org.au', 'Karata', '2016-05-27 18:17:24', 16, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jose', 'Day', 'password', 'jday14@dyndns.org', 'Shypyntsi', '2016-07-20 21:23:48', 35, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Beverly', 'Thomas', 'password', 'bthomas15@usda.gov', 'Naurskaya', '2016-05-06 05:31:43', 62, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Walter', 'Alvarez', 'password', 'walvarez16@miitbeian.gov.cn', 'Jitian', '2016-08-09 15:12:54', 99, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Kathryn', 'Williams', 'password', 'kwilliams17@baidu.com', 'Niamtougou', '2016-05-24 15:57:32', 71, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Elizabeth', 'Woods', 'password', 'ewoods18@com.com', 'Pavlovskiy Posad', '2016-08-31 20:15:03', 55, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Kenneth', 'Kelley', 'password', 'kkelley19@mayoclinic.com', 'Pecoro', '2016-07-31 11:05:14', 13, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Anna', 'King', 'password', 'aking1a@abc.net.au', 'Samanggen', '2016-10-07 13:51:55', 66, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Patricia', 'Bell', 'password', 'pbell1b@globo.com', 'Xinzhu', '2016-08-24 09:10:46', 81, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jonathan', 'Murphy', 'password', 'jmurphy1c@soundcloud.com', 'Semarang', '2016-03-20 20:44:29', 12, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Nicholas', 'Morales', 'password', 'nmorales1d@walmart.com', 'Alingsås', '2016-08-11 12:38:01', 53, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Donna', 'Murphy', 'password', 'dmurphy1e@tuttocitta.it', 'Goussainville', '2016-06-16 20:52:46', 23, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Brandon', 'Hughes', 'password', 'bhughes1f@tamu.edu', 'Marmande', '2016-03-09 19:33:53', 40, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Justin', 'Lewis', 'password', 'jlewis1g@so-net.ne.jp', 'Yamada', '2016-05-25 22:37:34', 37, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Stephanie', 'Jones', 'password', 'sjones1h@europa.eu', 'Nizhnevartovsk', '2016-02-18 20:56:19', 65, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jeffrey', 'Franklin', 'password', 'jfranklin1i@wired.com', 'Myrnyy', '2016-01-18 03:35:06', 81, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Donald', 'Davis', 'password', 'ddavis1j@addtoany.com', 'Zhangdian', '2016-03-20 01:44:01', 22, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Stephen', 'Fisher', 'password', 'sfisher1k@delicious.com', 'Xekar', '2016-06-11 00:01:38', 46, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Keith', 'Foster', 'password', 'kfoster1l@github.io', 'San Alberto', '2016-06-07 04:19:12', 49, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Martha', 'Wright', 'password', 'mwright1m@comsenz.com', 'Hal’shany', '2016-03-21 01:26:14', 49, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Pamela', 'Scott', 'password', 'pscott1n@hud.gov', 'Tupambaé', '2016-04-10 11:47:35', 80, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Carol', 'Ford', 'password', 'cford1o@nifty.com', 'Desa Gegempalan', '2016-02-21 23:15:37', 82, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jean', 'Wheeler', 'password', 'jwheeler1p@disqus.com', 'Hörby', '2016-02-10 16:14:09', 6, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Ashley', 'Torres', 'password', 'atorres1q@blogger.com', 'Ayní', '2016-03-18 08:37:54', 55, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Sarah', 'Ryan', 'password', 'sryan1r@acquirethisname.com', 'Kampungruweh', '2016-04-07 02:25:51', 95, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Cynthia', 'Stone', 'password', 'cstone1s@princeton.edu', 'Gunung Talang', '2016-03-08 17:07:16', 46, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Lillian', 'Henry', 'password', 'lhenry1t@paginegialle.it', 'Palon', '2016-01-09 06:05:46', 63, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Karen', 'Williams', 'password', 'kwilliams1u@miibeian.gov.cn', 'Genzi', '2016-01-30 08:44:32', 53, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Tammy', 'Williamson', 'password', 'twilliamson1v@devhub.com', 'Thị Trấn Than Uyên', '2016-08-30 22:22:30', 3, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Marilyn', 'Brooks', 'password', 'mbrooks1w@phoca.cz', 'Wadusari', '2016-08-06 15:03:51', 32, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Ronald', 'Riley', 'password', 'rriley1x@apple.com', 'Crespo', '2016-07-09 12:44:10', 35, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Shawn', 'Boyd', 'password', 'sboyd1y@behance.net', 'El Olivar', '2016-09-06 07:04:58', 63, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Frances', 'Hawkins', 'password', 'fhawkins1z@kickstarter.com', 'Qingjiangqiao', '2016-04-24 08:30:32', 67, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Melissa', 'Nelson', 'password', 'mnelson20@theguardian.com', 'Cértegui', '2016-02-19 08:27:04', 23, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Teresa', 'Banks', 'password', 'tbanks21@weather.com', 'Renhe', '2016-10-07 01:07:05', 58, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Carol', 'Burke', 'password', 'cburke22@berkeley.edu', 'Barili', '2016-01-17 15:10:48', 70, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Wayne', 'Clark', 'password', 'wclark23@homestead.com', 'Suwatu', '2016-08-22 09:58:48', 44, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Scott', 'Burke', 'password', 'sburke24@digg.com', 'Ballymun', '2016-01-30 15:56:22', 49, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Nancy', 'Dunn', 'password', 'ndunn25@google.co.jp', 'Guozhuang', '2016-05-10 06:21:32', 100, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Steve', 'Freeman', 'password', 'sfreeman26@aol.com', 'Basqal', '2016-05-12 07:17:51', 44, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Amy', 'Wilson', 'password', 'awilson27@instagram.com', 'Oro Verde', '2016-08-18 15:43:26', 10, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Annie', 'Sanders', 'password', 'asanders28@netscape.com', 'Menglie', '2016-07-23 19:56:23', 4, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Nancy', 'George', 'password', 'ngeorge29@indiegogo.com', 'Niedźwiedź', '2016-05-01 18:21:54', 42, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Chris', 'Johnson', 'password', 'cjohnson2a@jiathis.com', 'Landi Kotal', '2016-02-14 20:42:49', 42, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Joshua', 'Fisher', 'password', 'jfisher2b@seesaa.net', 'Aradac', '2016-06-10 15:14:38', 64, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Phillip', 'Ryan', 'password', 'pryan2c@ibm.com', 'Kyzyl-Kyya', '2016-01-21 01:49:10', 45, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Ann', 'Burke', 'password', 'aburke2d@cnn.com', 'Jāndiāla Sher Khān', '2016-04-15 03:34:21', 28, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Bonnie', 'Foster', 'password', 'bfoster2e@chicagotribune.com', 'Firmat', '2016-07-31 03:38:20', 45, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Patricia', 'Porter', 'password', 'pporter2f@comcast.net', 'Karlskrona', '2016-08-27 09:49:33', 96, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Judith', 'Jackson', 'password', 'jjackson2g@nasa.gov', 'El Corozal', '2016-05-28 14:52:10', 22, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Todd', 'Bowman', 'password', 'tbowman2h@google.it', 'Nantes', '2016-08-20 09:55:59', 43, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Clarence', 'Morrison', 'password', 'cmorrison2i@yolasite.com', 'Gandu', '2016-09-27 22:32:34', 73, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Dennis', 'Banks', 'password', 'dbanks2j@github.io', 'Gujiang', '2016-04-27 11:38:34', 30, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Mildred', 'Jacobs', 'password', 'mjacobs2k@yahoo.com', 'Yingshouyingzi', '2016-05-16 20:56:31', 40, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Beverly', 'Garza', 'password', 'bgarza2l@dailymotion.com', 'Yartsevo', '2016-04-01 07:19:14', 59, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Joe', 'Harvey', 'password', 'jharvey2m@barnesandnoble.com', 'Mikrókampos', '2016-05-12 23:02:02', 72, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Alan', 'Hanson', 'password', 'ahanson2n@usnews.com', 'Kochani', '2016-01-14 15:48:23', 94, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Julia', 'Richardson', 'password', 'jrichardson2o@boston.com', 'Nahrīn', '2016-08-20 20:05:38', 34, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Wayne', 'Thompson', 'password', 'wthompson2p@ning.com', 'Guantánamo', '2016-08-21 07:47:14', 48, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Maria', 'Nelson', 'password', 'mnelson2q@webnode.com', 'Fosca', '2016-08-01 23:24:39', 96, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Ernest', 'Payne', 'password', 'epayne2r@bizjournals.com', 'Ibeto', '2016-01-16 20:37:20', 11, 0);
