insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Kathleen', 'Stephens', 'password', 'kstephens0@narod.ru', 'Voloka', '20/05/2016', 50, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jimmy', 'Hudson', 'password', 'jhudson1@adobe.com', 'La Jicaral', '17/02/2016', 35, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Bobby', 'Long', 'password', 'blong2@yellowpages.com', 'Xiaochi', '18/06/2016', 85, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Beverly', 'Ramos', 'password', 'bramos3@theguardian.com', 'Vyksa', '16/10/2016', 45, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Janet', 'Larson', 'password', 'jlarson4@gnu.org', 'Genang', '15/05/2016', 9, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Cheryl', 'Kelley', 'password', 'ckelley5@flavors.me', 'Mimbaan Timur', '19/02/2016', 24, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Victor', 'White', 'password', 'vwhite6@typepad.com', 'Sumusţā as Sulţānī', '10/01/2016', 46, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Clarence', 'Stewart', 'password', 'cstewart7@storify.com', 'Zhangjiang', '13/09/2016', 86, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Ralph', 'Shaw', 'password', 'rshaw8@indiatimes.com', 'Janowice', '23/04/2016', 34, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jack', 'Stone', 'password', 'jstone9@aboutads.info', 'Gorbatovka', '13/01/2016', 77, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Bruce', 'Davis', 'password', 'bdavisa@arizona.edu', 'Luobei', '02/06/2016', 19, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Linda', 'Arnold', 'password', 'larnoldb@newsvine.com', 'Mizur', '06/05/2016', 72, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Wanda', 'Hunt', 'password', 'whuntc@joomla.org', 'Haveli', '08/04/2016', 42, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Patricia', 'Carter', 'password', 'pcarterd@admin.ch', 'Wonotirto', '09/01/2016', 82, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Mary', 'Ortiz', 'password', 'mortize@csmonitor.com', 'Podivín', '14/01/2016', 66, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Juan', 'Carter', 'password', 'jcarterf@printfriendly.com', 'Karabash', '24/06/2016', 63, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Larry', 'Fernandez', 'password', 'lfernandezg@skyrock.com', 'Gannan', '22/02/2016', 80, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('James', 'Hall', 'password', 'jhallh@cocolog-nifty.com', 'Geneng', '28/01/2016', 57, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Justin', 'Green', 'password', 'jgreeni@jiathis.com', 'Hayang', '19/09/2016', 27, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Victor', 'Gordon', 'password', 'vgordonj@comsenz.com', 'Québec', '19/03/2016', 31, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Stephen', 'Olson', 'password', 'solsonk@yahoo.com', 'Ariguaní', '20/06/2016', 80, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Lawrence', 'Richardson', 'password', 'lrichardsonl@state.tx.us', 'Ndano', '12/05/2016', 18, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jimmy', 'Harrison', 'password', 'jharrisonm@sohu.com', 'Georgetown', '24/07/2016', 93, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Douglas', 'Reid', 'password', 'dreidn@rediff.com', 'Ryūgasaki', '14/06/2016', 42, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Kenneth', 'Phillips', 'password', 'kphillipso@samsung.com', 'Sietesz', '27/02/2016', 9, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Lillian', 'Lynch', 'password', 'llynchp@businesswire.com', 'Grosuplje', '27/01/2016', 9, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Russell', 'Castillo', 'password', 'rcastilloq@nytimes.com', 'Krzczonów', '01/09/2016', 93, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Victor', 'Harris', 'password', 'vharrisr@harvard.edu', 'Castlemartyr', '06/06/2016', 85, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Justin', 'Wilson', 'password', 'jwilsons@tuttocitta.it', 'Thomastown', '27/03/2016', 87, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Dorothy', 'Hernandez', 'password', 'dhernandezt@pcworld.com', 'Guanjiabao', '07/07/2016', 24, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Mark', 'Dunn', 'password', 'mdunnu@epa.gov', 'Maceda', '03/04/2016', 57, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Elizabeth', 'Willis', 'password', 'ewillisv@house.gov', 'Horad Krychaw', '02/05/2016', 46, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Paul', 'Franklin', 'password', 'pfranklinw@soundcloud.com', 'Qitan', '06/01/2016', 21, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Wanda', 'Owens', 'password', 'wowensx@google.nl', 'Ílion', '08/08/2016', 27, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Catherine', 'Schmidt', 'password', 'cschmidty@icio.us', 'Jiuchenggong', '05/08/2016', 58, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Tina', 'Dean', 'password', 'tdeanz@cargocollective.com', 'Bununu Dass', '24/04/2016', 22, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Nancy', 'Larson', 'password', 'nlarson10@discovery.com', 'Wuli', '05/05/2016', 55, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Margaret', 'Armstrong', 'password', 'marmstrong11@wisc.edu', 'El Cobre', '24/09/2016', 66, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Wanda', 'Harper', 'password', 'wharper12@aboutads.info', 'Xilanqi', '08/10/2016', 40, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Michael', 'Holmes', 'password', 'mholmes13@dailymail.co.uk', 'Špišić-Bukovica', '04/03/2016', 42, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jerry', 'Martinez', 'password', 'jmartinez14@w3.org', 'Sarkanjut', '16/08/2016', 77, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Timothy', 'Chavez', 'password', 'tchavez15@cargocollective.com', 'Oranjestad', '01/01/2016', 36, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Benjamin', 'Johnson', 'password', 'bjohnson16@slashdot.org', 'Lucma', '08/07/2016', 98, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Amanda', 'Walker', 'password', 'awalker17@ifeng.com', 'Brejoeira', '17/06/2016', 96, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Elizabeth', 'Hansen', 'password', 'ehansen18@ucoz.com', 'Centralniy', '21/10/2016', 51, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Gerald', 'Adams', 'password', 'gadams19@friendfeed.com', 'Colonia Neuland', '18/07/2016', 79, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Sean', 'Payne', 'password', 'spayne1a@unesco.org', 'Hepingjie', '24/02/2016', 36, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Ann', 'Fuller', 'password', 'afuller1b@twitpic.com', 'Sarbīsheh', '17/09/2016', 47, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Catherine', 'Edwards', 'password', 'cedwards1c@squidoo.com', 'Puerto Iguazú', '02/04/2016', 25, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Henry', 'Fowler', 'password', 'hfowler1d@globo.com', 'Gangkoujie', '29/08/2016', 6, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Martin', 'Graham', 'password', 'mgraham1e@webnode.com', 'Bielsk Podlaski', '17/04/2016', 62, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jessica', 'Simmons', 'password', 'jsimmons1f@ed.gov', 'Piaocao', '19/04/2016', 16, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Alice', 'Gutierrez', 'password', 'agutierrez1g@accuweather.com', 'Tanshan', '07/06/2016', 6, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Joan', 'Williams', 'password', 'jwilliams1h@baidu.com', 'Hushi', '19/08/2016', 54, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Aaron', 'Armstrong', 'password', 'aarmstrong1i@tiny.cc', 'Kaliprak', '15/08/2016', 75, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Fred', 'Cooper', 'password', 'fcooper1j@ftc.gov', 'Sokolovo', '21/05/2016', 74, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Joan', 'Harvey', 'password', 'jharvey1k@howstuffworks.com', 'Newport', '10/02/2016', 85, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Joan', 'Alvarez', 'password', 'jalvarez1l@arstechnica.com', 'Tumxuk', '24/02/2016', 93, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Debra', 'Welch', 'password', 'dwelch1m@ovh.net', 'Bayan', '26/03/2016', 73, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Antonio', 'Russell', 'password', 'arussell1n@pbs.org', 'Magway', '05/03/2016', 87, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jessica', 'Clark', 'password', 'jclark1o@utexas.edu', 'Lafia', '19/09/2016', 66, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Sandra', 'Adams', 'password', 'sadams1p@jiathis.com', 'Kretinga', '13/08/2016', 33, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Gloria', 'Shaw', 'password', 'gshaw1q@examiner.com', 'Kharlu', '07/07/2016', 98, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Janice', 'Butler', 'password', 'jbutler1r@myspace.com', 'Smilavichy', '01/01/2016', 84, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Russell', 'Andrews', 'password', 'randrews1s@123-reg.co.uk', 'Łopuszna', '16/07/2016', 95, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Rose', 'Harrison', 'password', 'rharrison1t@ca.gov', 'Seria', '17/03/2016', 52, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Lori', 'Ramos', 'password', 'lramos1u@elegantthemes.com', 'Limushan', '21/05/2016', 32, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Arthur', 'Wilson', 'password', 'awilson1v@latimes.com', 'Aeka', '12/01/2016', 43, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Adam', 'Andrews', 'password', 'aandrews1w@seattletimes.com', 'Nantes', '13/04/2016', 54, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Joshua', 'Harvey', 'password', 'jharvey1x@java.com', 'Salitral', '09/06/2016', 53, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Alan', 'Wood', 'password', 'awood1y@hexun.com', 'Mekarjaya Satu', '25/02/2016', 45, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Albert', 'Howard', 'password', 'ahoward1z@wikimedia.org', 'Janaka', '24/03/2016', 16, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Anna', 'Larson', 'password', 'alarson20@cyberchimps.com', 'Kalangsari', '12/01/2016', 29, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Karen', 'Gilbert', 'password', 'kgilbert21@disqus.com', 'Bohicon', '20/09/2016', 91, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Sarah', 'Boyd', 'password', 'sboyd22@upenn.edu', 'Yongping', '28/09/2016', 27, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Tina', 'Welch', 'password', 'twelch23@is.gd', 'Conduaga', '24/04/2016', 41, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Steve', 'Olson', 'password', 'solson24@xrea.com', 'Irákleia', '01/01/2016', 90, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jeremy', 'Wallace', 'password', 'jwallace25@amazon.co.uk', 'Ābyek', '22/09/2016', 13, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Victor', 'Powell', 'password', 'vpowell26@imdb.com', 'Borgarnes', '12/04/2016', 28, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Richard', 'Olson', 'password', 'rolson27@biglobe.ne.jp', 'Kaga Bandoro', '10/05/2016', 39, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Harold', 'Evans', 'password', 'hevans28@businessweek.com', 'Maji', '06/02/2016', 91, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Norma', 'Montgomery', 'password', 'nmontgomery29@japanpost.jp', 'Maguyam', '23/07/2016', 40, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Louis', 'Anderson', 'password', 'landerson2a@sfgate.com', 'Zhushan', '21/07/2016', 90, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Antonio', 'Gibson', 'password', 'agibson2b@ehow.com', 'Wan’an', '10/03/2016', 35, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Ralph', 'Gibson', 'password', 'rgibson2c@wordpress.org', 'Montrouge', '22/07/2016', 76, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Katherine', 'Ferguson', 'password', 'kferguson2d@pbs.org', 'Shidu', '12/05/2016', 79, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Wanda', 'Rice', 'password', 'wrice2e@cdc.gov', 'Al Fākhūrah', '20/07/2016', 40, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Michelle', 'Evans', 'password', 'mevans2f@bloglovin.com', 'Tanbuqiao', '25/01/2016', 74, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Louis', 'Lawrence', 'password', 'llawrence2g@wufoo.com', 'Velyka Oleksandrivka', '31/01/2016', 81, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Earl', 'Torres', 'password', 'etorres2h@sakura.ne.jp', 'Ropa', '16/04/2016', 21, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Shawn', 'Richardson', 'password', 'srichardson2i@phoca.cz', 'Périgny', '01/03/2016', 34, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Donald', 'Patterson', 'password', 'dpatterson2j@utexas.edu', 'Leiyang', '31/01/2016', 8, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Sara', 'Perez', 'password', 'sperez2k@dmoz.org', 'Kedungasem', '01/05/2016', 27, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Jane', 'Larson', 'password', 'jlarson2l@google.fr', 'Ognevka', '28/05/2016', 55, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Albert', 'Hanson', 'password', 'ahanson2m@nih.gov', 'Celso Ramos', '05/04/2016', 44, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Benjamin', 'Carpenter', 'password', 'bcarpenter2n@abc.net.au', 'Tangban', '26/03/2016', 70, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Bruce', 'Day', 'password', 'bday2o@t.co', 'Xiangxi', '10/03/2016', 51, 0);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Sandra', 'Torres', 'password', 'storres2p@nih.gov', 'Citeureup', '21/04/2016', 86, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Peter', 'Armstrong', 'password', 'parmstrong2q@weebly.com', 'Dulangan', '02/03/2016', 78, 1);
insert into players (firstname, lastname, password, email, town, regdate, logins, banned) values ('Alice', 'Reid', 'password', 'areid2r@house.gov', 'Tuqiao', '10/08/2016', 33, 0);
